/** 每個伺服器的預設設定（新伺服器第一次使用時深層合併） */
const DEFAULTS = {
  prefix: '!',
  welcome: {
    enabled: false,
    channel: null,
    message: null,
    dm: false,
    dmMessage: null,
    verifyHint: null,
    deleteAfter: null,
  },
  goodbye: {
    enabled: false,
    channel: null,
    message: null,
  },
  verify: {
    enabled: false,
    role: null,
    channel: null,
    panelMessage: null,
    buttonLabel: '✅ 點我驗證',
    buttonEmoji: null,
    message: null,
    autoRemoveOnLeave: false,
  },
  autoroles: [],
  logs: {
    enabled: false,
    channel: null,
    events: {
      messageEdit: true,
      messageDelete: true,
      memberJoin: true,
      memberLeave: true,
      memberUpdate: true,
      channelCreate: true,
      channelDelete: true,
      roleCreate: true,
      roleDelete: true,
      ban: true,
      unban: true,
      voice: true,
    },
  },
  tickets: {
    enabled: false,
    category: null,
    supportRole: null,
    channel: null,
    panelMessage: null,
    transcriptChannel: null,
    maxTickets: 3,
    welcomeMessage: null,
    closeDeleteAfter: 3600000,
  },
  automod: {
    enabled: false,
    bannedWords: [],
    invites: false,
    links: false,
    caps: false,
    capsPercent: 70,
    capsMinLength: 8,
    mentions: false,
    mentionLimit: 5,
    spam: false,
    spamThreshold: 5,
    spamWindow: 6000,
    duplicate: false,
    duplicateThreshold: 3,
    duplicateWindow: 60000,
    action: 'delete',
    ignoreChannels: [],
  },
  antiRaid: {
    enabled: false,
    action: 'ban',
    threshold: 5,
    window: 10000,
  },
  leveling: {
    enabled: true,
    announce: false,
    channel: null,
    xpPerMessage: 15,
    cooldown: 60000,
    roles: {},
    ignoreChannels: [],
  },
  economy: {
    enabled: true,
    currency: '🪙',
    daily: 500,
    weekly: 2500,
    workMin: 100,
    workMax: 300,
    workCooldown: 3600000,
    begMin: 1,
    begMax: 30,
    begCooldown: 45000,
    shop: [],
  },
  suggestions: {
    enabled: false,
    channel: null,
  },
  stats: {
    enabled: false,
    category: null,
    channels: { members: null, humans: null, bots: null, online: null, boosters: null },
  },
  tempVoice: {
    enabled: false,
    createChannel: null,
    category: null,
    nameTemplate: '🔊 {user} 的頻道',
  },
  reactionRoles: [],
  customCommands: {},
  birthdays: {
    channel: null,
    role: null,
  },
  music: {
    enabled: true,
    djRole: null,
    defaultVolume: 60,
    maxDuration: null,
  },
  guide: {
    enabled: false,
    channel: null,
    messageId: null,
  },
  modlogChannel: null,
};

module.exports = { DEFAULTS };
